### ISSUE TITLE
Broken path in head inside folders

### ISSUE THREAD

**Issue by Atilogit** [Kobzol/cargo-remark#4]
When using a normal project structure like the following
```
root
|- src
|  |- main.rs
|- Cargo.toml
```
the links inside the `<head>` are invalid.
cargo-remark produces
```html
<link rel="stylesheet" type="text/css" href="../assets/css/codemirror-5.65.13.min.css">
<script src="../assets/js/jquery-3.5.1.min.js"></script>
<script src="../assets/js/codemirror-5.65.13.min.js"></script>
<script src="../assets/js/codemirror-5.65.13-simple.min.js"></script>
<script src="../assets/js/codemirror-5.65.13-rust.min.js"></script>
```
which can't be found by the browser because it points to `target/remarks/web/src/assets/...` instead of `target/remarks/web/assets/...`.

The same issue applies when using folders as rust modules and when using multiple crates in a workspace.

**Comment by Kobzol** [comment]
Hi, I can't reproduce this. For the project structure that you have sent, this website directory is generated:
```
web
|- index.html
|- remarks.html
|- assets
|- src
   - src_main.rs.html
```
And `src_main.rs.html` contains the `../assets/js/jquery-3.5.1.min.js` link, which correctly points to `web/assets/...`.

**Comment by Kobzol** [comment]
Oh, right, sorry for that. Windows support is really experimental in this crate, I'm afraid. Could you please try if this solves the issue for you?
```bash
$ cargo install --git https://github.com/Kobzol/cargo-remark --branch path-separator
```

**Comment by Atilogit** [comment]
Yes it does. Thank you!
