### ISSUE TITLE
Incorrect javascript paths

### ISSUE THREAD

**Issue by bugadani** [Kobzol/cargo-remark#6]
The generated static website assumes that all generated HTML files are located in the root of `src/`, which makes the `../assets` links in the HTMLs incorrect if this assumption does not hold.

**Comment by Kobzol** [comment]
Hi, the tool should generate all source files in the src directory (apart from index.html and remarks.html). Did it generate files in some nested directory, or elsewhere?

**Comment by bugadani** [comment]
The tool nested the files, `src/main.rs`'s results were placed into `src/src/main.rs.html`. I am wondering if the library results got scattered around my filesystem now :D 

Here's how the folder structure looks like:

![image](https://github.com/Kobzol/cargo-remark/assets/977627/ce4e9406-54a5-49da-b229-2505d64a9809)

**Comment by bugadani** [comment]
I should add that I'm trying this on Windows, so I have a bunch of `src/C:\Users\bugad\.cargo\registry` paths, too, but that is somewhat of a different issue

**Comment by Kobzol** [comment]
Sorry for that, this crate is not well tested on Windows, and I already saw several similar issues. Are you using the newest version of the crate?

I'm on a vacation now, I'll take a look at it at the beginning of September.

**Comment by bugadani** [comment]
I've just installed yesterday, so probably the latest, yes.

No worries, enjoy your vacation!

**Comment by Kobzol** [comment]
Can you please check if this branch fixes your issue?
```bash
$ cargo install --git https://github.com/Kobzol/cargo-remark --branch path-normalization
```

**Comment by bugadani** [comment]
Thanks, it seems this particular issue is indeed fixed using that branch.
