### ISSUE TITLE
JS is trying to load images that don't exist

### ISSUE THREAD

**Issue by bugadani** [Kobzol/cargo-remark#9]
I noticed this while testing the fixed path normalization. Looks like the remarks list is supposed to have some arrows that aren't present in the generated output (or the template, for that matter).

![image](https://github.com/Kobzol/cargo-remark/assets/977627/e057149f-f293-4599-bc3e-16f7da1fdb70)

**Comment by Kobzol** [comment]
Thanks, I didn't notice this. The linked PR should fix this.

**Comment by bugadani** [comment]
Thank you!
